Repository Giljjang/Tourding_FE, pull requests merged in 2025-08, with the labels that each got.

#3 [Chore]: Tab 폴더 관리 및 디자인 시스템 hex값 수정
  Tourding_FE.xcodeproj/project.pbxproj
  Tourding_FE.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tourding_FE/App/DependencyProvider.swift
  Tourding_FE/Extenstion/Color+Hex.swift
  Tourding_FE/Model/TabViewModelsContainer.swift
  Tourding_FE/Resources/Assets.xcassets/TabView/Contents.json
  Tourding_FE/Resources/Assets.xcassets/TabView/riding_off.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/TabView/riding_off.imageset/icon_Creating a Route (1).svg
  Tourding_FE/Resources/Assets.xcassets/TabView/riding_on.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/TabView/riding_on.imageset/icon_Creating a Route.svg
  Tourding_FE/Resources/Assets.xcassets/TabView/spot_off.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/TabView/spot_off.imageset/icon_Finding a Travel Destination.svg
  Tourding_FE/Resources/Assets.xcassets/TabView/spot_on.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/TabView/spot_on.imageset/icon_Finding a Travel Destination (1).svg
  Tourding_FE/Resources/Assets.xcassets/TabView/user_off.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/TabView/user_off.imageset/icon_My information.svg
  Tourding_FE/Resources/Assets.xcassets/TabView/user_on.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/TabView/user_on.imageset/icon_My information (1).svg
  Tourding_FE/Resources/Assets.xcassets/riding/Contents.json
  Tourding_FE/Resources/Assets.xcassets/riding/chevron-right.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/riding/chevron-right.imageset/icon_chevron-right.svg
  Tourding_FE/Resources/Assets.xcassets/riding/dot_line.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/riding/dot_line.imageset/icon_ dotted lines.svg
  Tourding_FE/Resources/Assets.xcassets/riding/endpoint.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/riding/endpoint.imageset/icon_destination.svg
  Tourding_FE/Resources/Assets.xcassets/riding/icon_right.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/riding/icon_right.imageset/icon_right.svg
  Tourding_FE/Resources/Assets.xcassets/riding/logo.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/riding/logo.imageset/logo.svg
  Tourding_FE/Resources/Assets.xcassets/riding/route.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/riding/route.imageset/Group 35448.svg
  Tourding_FE/Resources/Assets.xcassets/riding/startpoint.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/riding/startpoint.imageset/icon_point of departure.svg
  Tourding_FE/ViewModels/Riding/RidingViewModel.swift
  Tourding_FE/ViewModels/SpotSearch/SpotSearchViewModel.swift
  Tourding_FE/ViewModels/Tab/NavigationManager.swift
  Tourding_FE/ViewModels/TourRecommendation/TourRecommendationViewModel.swift
  Tourding_FE/Views/Components/CustomTabView.swift
  Tourding_FE/Views/Home/HomeView.swift
  Tourding_FE/Views/Riding/NaverMapView.swift
  Tourding_FE/Views/Riding/RidingView.swift
  Tourding_FE/Views/Riding/RouteContinueModal.swift
  Tourding_FE/Views/SpotSearch/SpotSearchView.swift
  Tourding_FE/Views/Tab/CustomTabView.swift
  Tourding_FE/Views/Tab/TabContentView.swift
Labels: Refactor, UI

#5 Jh: LiginView MVVM으로 쪼갬
  Tourding_FE.xcodeproj/project.pbxproj
  Tourding_FE/App/Tourding_FEApp.swift
  Tourding_FE/Extenstion/Color+Hex.swift
  Tourding_FE/Resources/Assets.xcassets/Login/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Login/apple.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Login/apple.imageset/apple 1.png
  Tourding_FE/Resources/Assets.xcassets/Login/apple.imageset/apple 2.png
  Tourding_FE/Resources/Assets.xcassets/Login/apple.imageset/apple.png
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_1.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_1.imageset/illust_login 1.png
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_1.imageset/illust_login 2.png
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_1.imageset/illust_login.png
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_2.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_2.imageset/illust_onboarding_1 1.png
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_2.imageset/illust_onboarding_1 2.png
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_2.imageset/illust_onboarding_1.png
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_3.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_3.imageset/illust_onboarding_2 1.png
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_3.imageset/illust_onboarding_2 2.png
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_3.imageset/illust_onboarding_2.png
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_4.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_4.imageset/illust_onboarding_3 1.png
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_4.imageset/illust_onboarding_3 2.png
  Tourding_FE/Resources/Assets.xcassets/Login/illust_login_4.imageset/illust_onboarding_3.png
  Tourding_FE/Resources/Assets.xcassets/Login/kakao.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Login/kakao.imageset/kakao 1.png
  Tourding_FE/Resources/Assets.xcassets/Login/kakao.imageset/kakao 2.png
  Tourding_FE/Resources/Assets.xcassets/Login/kakao.imageset/kakao.png
  Tourding_FE/ViewModels/Login/LoginViewModel.swift
  Tourding_FE/Views/Login/LoginStruct.swift
  Tourding_FE/Views/Login/LoginView.swift
  Tourding_FE/Views/Login/OnboardingPageView.swift
  Tourding_FE/Views/MyPage/MyPageView.swift
Labels: Refactor

#8 [UI]: riding sheet UI 완료
  Tourding_FE/App/DependencyProvider.swift
  Tourding_FE/App/Tourding_FEApp.swift
  Tourding_FE/Model/Riding/RidingSpotModel.swift
  Tourding_FE/Model/TabViewModelsContainer.swift
  Tourding_FE/Resources/Assets.xcassets/Home/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Home/chevron-right.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Home/chevron-right.imageset/icon_chevron-right.svg
  Tourding_FE/Resources/Assets.xcassets/Home/dot_line.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Home/dot_line.imageset/icon_ dotted lines.svg
  Tourding_FE/Resources/Assets.xcassets/Home/endpoint.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Home/endpoint.imageset/icon_destination.svg
  Tourding_FE/Resources/Assets.xcassets/Home/home_logo.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Home/home_logo.imageset/logo.svg
  Tourding_FE/Resources/Assets.xcassets/Home/icon_right.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Home/icon_right.imageset/icon_right.svg
  Tourding_FE/Resources/Assets.xcassets/Home/route.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Home/route.imageset/Group 35448.svg
  Tourding_FE/Resources/Assets.xcassets/Home/startpoint.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Home/startpoint.imageset/icon_point of departure.svg
  Tourding_FE/Resources/Assets.xcassets/Riding/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Riding/icon_destination.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Riding/icon_destination.imageset/icon_destination.svg
  Tourding_FE/Resources/Assets.xcassets/Riding/icon_plus.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Riding/icon_plus.imageset/icon_plus.svg
  Tourding_FE/Resources/Assets.xcassets/Riding/icon_point.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Riding/icon_point.imageset/icon_point of departure.svg
  Tourding_FE/Resources/Assets.xcassets/Riding/riding_back.imageset/Contents.json
  Tourding_FE/Resources/Assets.xcassets/Riding/riding_back.imageset/icon_chevron-left.svg
  Tourding_FE/ViewModels/Components/ModalManager.swift
  Tourding_FE/ViewModels/Home/HomeViewModel.swift
  Tourding_FE/ViewModels/Riding/RidingViewModel.swift
  Tourding_FE/ViewModels/Tab/NavigationManager.swift
  Tourding_FE/Views/Home/HomeView.swift
  Tourding_FE/Views/Home/NaverMapView.swift
  Tourding_FE/Views/MyPage/MyPageView.swift
  Tourding_FE/Views/Riding/CustomBottomSheet.swift
  Tourding_FE/Views/Riding/RidingView.swift
  Tourding_FE/Views/Riding/SheetContentView.swift
  Tourding_FE/Views/Riding/SpotDropDelegate.swift
  Tourding_FE/Views/Tab/CustomTabView.swift
  Tourding_FE/Views/Tab/TabContentView.swift
Labels: Feat, Refactor, UI
